---
title: "Simulating clinical trials, various simulations"
author: "Steve Simon"
date: "March 22, 2017"
output: html_document
---

```{r preliminaries, echo=FALSE, message=FALSE}
source("0-preliminaries.R", echo=FALSE)
```

```{r simulate-time-prelims}
# I'm going to cheat here. A proper simulation would use
#   lambda <- rgamma(1, N*S, T*S)
# but to make the plots look a bit cleaner, I'm going to
# deliberately choose from the left tail
# and then the right tail of this gamma distribution.

lambda_list <- c(
  qgamma(runif(1, 0.01, 0.1),  N*S, T*S),
  qgamma(runif(1, 0.9,  0.99), N*S, T*S))

n_lambda <- length(lambda_list)
lambda <- rep(lambda_list, each=N)
n <- rep(1:N, n_lambda)
t <- rexp(n_lambda*N, lambda)
g <- rep(1:n_lambda, each=N)

data.frame(n, t, g)                             %>%
  group_by(g)                                   %>%
  mutate(t=cumsum(t))                           %>%
  ungroup                                       -> simulated_paths

simulated_paths                                 %>%
  group_by(g)                                   %>%
  summarize(t=max(t))                           %>%
  mutate(t=round(t))                            %>%
  mutate(n=N)                                   -> endpoints

x_breaks <- 182.5*(0:10)
y_breaks <- 50*(0:9)

simulated_paths                                 %>%
  ggplot(aes(x=t, y=n, group=g))                 +
    theme(axis.title = element_text(color=dk))     +
    theme(axis.text = element_text(color=dk))      +
    theme(axis.ticks = element_line(color=dk))     +
    theme(panel.background=element_rect(fill=lt)) +
  scale_x_continuous(breaks=x_breaks)            +
  scale_y_continuous(breaks=y_breaks)            +
  geom_hline(yintercept=y_breaks, col="white")   +
  expand_limits(x=365*3.7, y=450)                +
  geom_line()                                    +
  geom_hline(yintercept=N)                       + 
  geom_vline(xintercept=T, color="gray")         + 
  xlab("Time (days)")                            +
  ylab("Number of patients")                     +
  geom_label(data=endpoints,
             aes(t, n, label=t),
             size=2.5)                          -> fig
save(fig, file="fig/1.1.RData")
```

### Figure 1.1. Simulation of a clinical trial with a fixed sample size.

```{r simulate-time, fig.width=10, fig.height=5, eval=TRUE}
# sometimes I will want to limit evaluations of lengthy sections
# of code. Then I can specify eval=FALSE in the global options
# and include eval=TRUE on the key sections like this one.
load("fig/1.1.Rdata")
print(fig)
```

```{r simulate-n-prelimis}
lambda_list <- c(
  qgamma(runif(1, 0.01, 0.1),  N*S, T*S),
  qgamma(runif(1, 0.9,  0.99), N*S, T*S))

n_lambda <- length(lambda_list)
lambda <- rep(lambda_list, each=T)
t <- rep(1:T, n_lambda)
n <- rpois(n_lambda*T, lambda)
g <- rep(1:n_lambda, each=T)

data.frame(n, t, g)                             %>%
  group_by(g)                                   %>%
  mutate(n=cumsum(n))                           %>%
  ungroup                                       -> simulated_paths

simulated_paths                                 %>%
  group_by(g)                                   %>%
  summarize(n=max(n))                           %>%
  mutate(t=T)                                   -> endpoints

simulated_paths                                 %>%
  ggplot(aes(x=t, y=n, group=g))                 +
  scale_x_continuous(breaks=x_breaks)            +
  scale_y_continuous(breaks=y_breaks)            +
  expand_limits(x=365*3.7, y=450)                +
  geom_line()                                    +
  geom_hline(yintercept=N, color="gray")         + 
  geom_vline(xintercept=T)                       + 
  xlab("Time (days)")                            +
  ylab("Number of patients")                     +
  geom_label(data=endpoints,
             aes(t, n, label=n),
             size=2.5)                          -> fig
save(fig, file="fig/1.2.RData")
```

### Figure 1.2. Simulation of a clinical trial with a fixed time frame.

```{r simulate-n, fig.width=10, fig.height=5}
load("fig/1.2.RData")
print(fig)
```

```{r simulate-composite-prelims}
lambda_list <- c(
  qgamma(runif(1, 0.01, 0.1),  N*S, T*S),
  qgamma(runif(1, 0.9,  0.99), N*S, T*S))

n_lambda <- length(lambda_list)
lambda <- rep(lambda_list, each=N)
n <- rep(1:N, n_lambda)
t <- rexp(n_lambda*N, lambda)
g <- rep(1:n_lambda, each=N)

data.frame(n, t, g)                             %>%
  group_by(g)                                   %>%
  mutate(t=cumsum(t))                           %>%
  mutate(t=trunc(t))                            %>%
  mutate(t=pmin(t, T))                          %>%
  distinct(t, .keep_all=TRUE)                   %>%
  ungroup                                       -> simulated_paths

simulated_paths                                 %>%
  group_by(g)                                   %>%
  summarize(t=max(t), n=max(n))                 %>%
  mutate(lb=paste(t, n, sep=", "))              -> endpoints

simulated_paths                                 %>%
  ggplot(aes(x=t, y=n, group=g))                 +
  scale_x_continuous(breaks=x_breaks)            +
  scale_y_continuous(breaks=y_breaks)            +
  expand_limits(x=365*3.7, y=450)                +
  geom_line()                                    +
  geom_hline(yintercept=N)                       + 
  geom_vline(xintercept=T)                       + 
  xlab("Time (days)")                            +
  ylab("Number of patients")                     +
  geom_label(data=endpoints,
             aes(t, n, label=lb),
             size=2.5)                          -> fig
save(fig, file="fig/1.3.RData")
```

### Figure 1.3. Simulation of a trial with a conditional endpoint.

```{r simulate-composite, fig.width=10, fig.height=5, eval=TRUE}
load("fig/1.3.RData")
print(fig)
```

```{r simulate-cost-prelims}
lambda_list <- c(
  qgamma(runif(1, 0.01, 0.1),  N*S, T*S),
  qgamma(runif(1, 0.9,  0.99), N*S, T*S))

n_lambda <- length(lambda_list)
lambda <- rep(lambda_list, each=N)
n <- rep(1:N, n_lambda)
t <- rexp(n_lambda*N, lambda)
g <- rep(1:n_lambda, each=N)

data.frame(n, t, g)                             %>%
  group_by(g)                                   %>%
  mutate(t=cumsum(t))                           %>%
  mutate(t=trunc(t))                            %>%
  mutate(t=pmin(t, T))                          %>%
  distinct(t, .keep_all=TRUE)                   %>%
  ungroup                                       -> simulated_paths

simulated_paths                                 %>%
  group_by(g)                                   %>%
  summarize(t=max(t), n=max(n))                 %>%
  mutate(lb=80*t+20*n)                        %>%
  mutate(lb=format(lb, big.mark=","))           %>%
  mutate(lb=paste("£", lb, sep=""))             -> endpoints

x_breaks                                        %>%
  multiply_by(80)                               %>%
  prettyNum(big.mark=",", width=10)             %>%
  gsub(" ", "", .)                              %>%
  paste("£", ., sep="")                         -> x_labels

y_breaks                                        %>%
  multiply_by(20)                               %>%
  prettyNum(big.mark=",")                       %>%
  gsub(" ", "", .)                              %>%
  paste("£", ., sep="")                         -> y_labels


simulated_paths                                 %>%
  ggplot(aes(x=t, y=n, group=g))                 +
  geom_line()                                    +
  scale_x_continuous(
    breaks=x_breaks,
    labels=x_labels)                             +
  scale_y_continuous(
    breaks=y_breaks,
    labels=y_labels)                             +
  expand_limits(x=365*3.7, y=450)                +
  geom_hline(yintercept=N)                       + 
  geom_vline(xintercept=T)                       + 
  xlab("Time cost")                              +
  ylab("Patient cost")                           +
  geom_label(
    data=endpoints,
    aes(t, n, label=lb),
    size=2.5)                                   -> fig
save(fig, file="fig/1.4.RData")
```

### Figure 1.4. Simulation of the cost of a clinical trial. 

```{r simulate-cost, fig.width=10, fig.height=5, eval=TRUE}
load("fig/1.4.RData")
print(fig)
```

```{r save-everything}
save.image("1-various-simulations.RData")
```
