---
title: "Simulating clinical trials, paths in a simulation"
author: "Steve Simon"
date: "March 22, 2017"
output: html_document
---

```{r preliminaries, message=FALSE, echo=FALSE}
source("0-preliminaries.R", echo=FALSE)
dat_prior <- list(N=N, T=T, S=S)
pts <- unlist(read.csv("2-paths-count.csv"))
dat_updated <- list(N=N, T=T, S=S, n=pts, t=length(pts))
```

### Part 2.  Paths in a simulation

```{r path2-prelims, message=FALSE, warning=FALSE}
# For some reason, Stan is very slow for this simulation. 
x <- rep((t+1):T, each=n_reps)
j <- rep(1:n_reps, T-t)
lambda <- rep(rgamma(n_reps, N*S+n, T*S+t), T-t)
p <- rpois(n_reps*(T-t), lambda)
df <- data.frame(x=x, j=j, p=p)
df                                              %>%
  group_by(j)                                   %>%
  mutate(y=cumsum(p)+sum(pts))                  %>%
  ungroup                                       %>%
  group_by(x)                                   %>%
  summarize(
    q01=round(quantile(y, probs=0.01)), 
    q25=round(quantile(y, probs=0.25)), 
    q50=round(quantile(y, probs=0.50)), 
    q75=round(quantile(y, probs=0.75)), 
    q99=round(quantile(y, probs=0.99)))         %>%
  mutate(q01=round(q01))                        %>%
  mutate(q99=round(q99))                        %>%
  ungroup                                       %>%
  data.frame                                    -> sim_tr2

df                                              %>%
  filter(j==1)                                  %>%
  mutate(y1=cumsum(p)+sum(pts))                 %>%
  select(y1)                                    -> path1

df                                              %>%
  filter(j==2)                                  %>%
  mutate(y2=cumsum(p)+sum(pts))                 %>%
  select(y2)                                    -> path2

sim_tr2                                         %>%
  filter(x==T)                                  %>%
  select(q01, q25, q50, q75, q99)               %>%
  unlist                                        -> y_ticks
y_ticks                                         %>%
  round                                         %>%
  paste0(" (", pctl_list, "%)")                 -> y_labels

path0 <- data.frame(x=1:length(pts), y0=cumsum(pts))

sim_tr2 %>%
  bind_cols(path1)                              %>%
  bind_cols(path2)                              %>%
  full_join(path0)                              %>%
  ggplot(aes(x, ymin=q01, ymax=q99))             +
  expand_limits(x=c(0, 1336))                    +
  geom_ribbon(fill="gray")                       +
  geom_line(aes(y=q01),col="white")              +
  geom_line(aes(y=q25),col="white")              +
  geom_line(aes(y=q50),col="white")              +
  geom_line(aes(y=q75),col="white")              +
  geom_line(aes(y=q99),col="white")              +
  geom_line(aes(y=y1), col="black")              +
  geom_line(aes(y=y2), col="black")              +
  scale_x_continuous(breaks=365*(0:3))           +
  scale_y_continuous(breaks=y_ticks,
                     labels=y_labels,
                     minor=NULL)                 +
  xlab("Time (days)")                            +
  ylab("Estimated number of patients (Update)")  +
  geom_line(aes(y=y0))                           +
  expand_limits(y=500)                          -> fig
save(fig, file="fig/2.2.RData")
```



```{r path1-prelims, message=FALSE, warning=FALSE}
# For some reason, Stan is very slow for this simulation. 
x <- rep(1:T, each=n_reps)
j <- rep(1:n_reps, T)
lambda <- rep(rgamma(n_reps, N*S, T*S), T)
p <- rpois(n_reps*T, lambda)
df <- data.frame(x=x, j=j, p=p)
df                                              %>%
  group_by(j)                                   %>%
  mutate(y=cumsum(p))                           %>%
  ungroup                                       %>%
  group_by(x)                                   %>%
  summarize(
    q01=round(quantile(y, probs=0.01)), 
    q25=round(quantile(y, probs=0.25)), 
    q50=round(quantile(y, probs=0.50)), 
    q75=round(quantile(y, probs=0.75)), 
    q99=round(quantile(y, probs=0.99)))         %>%
  mutate(q01=round(q01))                        %>%
  mutate(q99=round(q99))                        %>%
  ungroup                                       %>%
  data.frame                                    -> sim_tr1

df                                              %>%
  filter(j==1)                                  %>%
  mutate(y1=cumsum(p))                          %>%
  select(y1)                                    -> path1

df                                              %>%
  filter(j==2)                                  %>%
  mutate(y2=cumsum(p))                          %>%
  select(y2)                                    -> path2

sim_tr1                                         %>%
  filter(x==T)                                  %>%
  select(q01, q25, q50, q75, q99)                %>%
  unlist                                        -> y_ticks
y_ticks                                         %>%
  round                                         %>%
  paste0(" (", pctl_list, "%)")                 -> y_labels


sim_tr1 %>%
  bind_cols(path1)                              %>%
  bind_cols(path2)                              %>%
  ggplot(aes(x, ymin=q01, ymax=q99))             +
  geom_ribbon(fill="gray")                       +
  geom_line(aes(y=q01),col="white")              +
  geom_line(aes(y=q25),col="white")              +
  geom_line(aes(y=q50),col="white")              +
  geom_line(aes(y=q75),col="white")              +
  geom_line(aes(y=q99),col="white")              +
  geom_line(aes(y=y1), col="black")              +
  geom_line(aes(y=y2), col="black")              +
  scale_x_continuous(breaks=365*(0:3))           +
  scale_y_continuous(breaks=y_ticks,
                     labels=y_labels,
                     minor=NULL)                 +
  xlab("Time (days)")                            +
  ylab("Estimated number of patients (Prior)")   +
  expand_limits(x=c(0, 1336))                    +
  expand_limits(y=500)                          -> fig
save(fig, file="fig/2.1.RData")
```

### Figure 2.1. 1000 simulations run prior to start of a clinical trial.

```{r path1, fig.width=10, fig.height=5, eval=TRUE}
load("fig/2.1.RData")
print(fig)
```

### Figure 2.2. 1000 simulations run during a clinical trial.

```{r path2, fig.width=10, fig.height=5, eval=TRUE}
load("fig/2.2.RData")
print(fig)
```

```{r path3-prelims-1}
# I do not have the exact path to the final result, but I do know that
# this trial ended on day 1336 with 341 patients. So it is easy to make
# a realistic looking path from day 239 with 41 patients.
x1 <- rpois(2000, 350/1095)
x2 <- x1[x1>0]
x3 <- cumsum(x2)
x4 <- min(which(x3>=(341-41)))
x5 <- x2[1:x4]
x5[x4] <- x5[x4] - (x3[x4]-(341-41))
x6 <- c(rep(0, (1336-239-1-length(x5))), x5)
x7 <- sample(x6)
x8 <- cumsum(c(pts,x7))
pathx <- data.frame(x=1:1336, yz=x8)
```

```{r path3-prelims-2}
sim_tr1 %>%
  full_join(pathx)                              %>%
  ggplot(aes(x, ymin=q01, ymax=q99))             +
  geom_ribbon(fill="gray")                       +
  geom_line(aes(y=q01),col="white")              +
  geom_line(aes(y=q25),col="white")              +
  geom_line(aes(y=q50),col="white")              +
  geom_line(aes(y=q75),col="white")              +
  geom_line(aes(y=q99),col="white")              +
  geom_line(aes(y=yz), col="red")                +
  scale_x_continuous(breaks=365*(0:3))           +
  scale_y_continuous(breaks=y_ticks,
                     labels=y_labels,
                     minor=NULL)                 +
  xlab("Time (days)")                            +
  ylab("Number of patients (Post mortem)")       +
  geom_label(aes(x=1336, y=341, 
                 label="(1336,341)"),
             col="red") +
  expand_limits(y=500)                          -> fig
save(fig, file="fig/2.3.RData")
```

### Figure 2.3. Post mortem examination of actual trial results.

```{r path3, fig.width=10, fig.height=5, eval=TRUE}
load("fig/2.3.RData")
print(fig)
```

```{r save-everything}
save.image("2-paths.RData")
```
