---
title: "Simulating clinical trials"
author: "Steve Simon"
date: "March 22, 2017"
output: html_document
---

```{r preliminaries, echo=FALSE, message=FALSE}
source("0-preliminaries.R", echo=FALSE)
p_list <- c(0.25, 0.75)
```


```{r early-predictions-flat-prelims-1}
# stan is inefficient for these next couple of models, but I'm not
# sure why. It is easy enough to run a simulation directly.
n_reps <- 100000
pts <- unlist(read.csv("2-paths-count.csv"))
x <- cumsum(pts)
T <- 3*365
N <- 350
alpha.prior <- 0.001
beta.prior  <- 0.001
nx <- length(x)
flat_predictions <- data.frame(t=1:nx, lo=rep(0,nx), hi=rep(0,nx))
for (i in seq(1, nx, by=1)) {
  alpha.posterior <- alpha.prior + x[i]
  beta.posterior  <- beta.prior + i
  lambda <- rgamma(n_reps, alpha.posterior, beta.posterior)
  waiting_time <- i + rgamma(n_reps, N-x[i], lambda)
  qx <- quantile(waiting_time, probs=p_list)
  flat_predictions[i, 2:3] <- qx
}
```

```{r early-predictions-strong-prelims-1}
n_reps <- 100000
pts <- unlist(read.csv("2-paths-count.csv"))
x <- cumsum(pts)
T <- 3*365
N <- 350
S <- 0.5
alpha.prior <- N*S
beta.prior  <- T*S
nx <- length(x)
informative_predictions <- data.frame(t=1:nx, lo=rep(0,nx), hi=rep(0,nx))
for (i in seq(1, nx, by=1)) {
  alpha.posterior <- alpha.prior + x[i]
  beta.posterior  <- beta.prior + i
  lambda <- rgamma(n_reps, alpha.posterior, beta.posterior)
  waiting_time <- i + rgamma(n_reps, N-x[i], lambda)
  qx <- quantile(waiting_time, probs=p_list)
  informative_predictions[i, 2:3] <- qx
}
```

```{r early-predictions-weak-prelims-1}
n_reps <- 100000
pts <- unlist(read.csv("2-paths-count.csv"))
x <- cumsum(pts)
T <- 3*365
N <- 350
S <- 0.02
alpha.prior <- N*S
beta.prior  <- T*S
nx <- length(x)
weak_predictions <- data.frame(t=1:nx, lo=rep(0,nx), hi=rep(0,nx))
for (i in seq(1, nx, by=1)) {
  alpha.posterior <- alpha.prior + x[i]
  beta.posterior  <- beta.prior + i
  lambda <- rgamma(n_reps, alpha.posterior, beta.posterior)
  waiting_time <- i + rgamma(n_reps, N-x[i], lambda)
  qx <- quantile(waiting_time, probs=p_list)
  weak_predictions[i, 2:3] <- qx
}
```

```{r early-predictions-flat-prelims-2}
flat_predictions                                %>%
  bind_rows(informative_predictions)            %>%
  bind_rows(weak_predictions)                   %>%
  summarize(hi=max(hi), lo=min(lo))             %>%
  unlist                                        %>%
  divide_by(365)                                -> overall_range
flat_predictions                                %>%
  mutate(lo=lo/365)                             %>%
  mutate(hi=hi/365)                             %>%
  ggplot(aes(x=t, ymin=lo, ymax=hi))             + 
  # expand_limits(y=overall_range)                 +
  # scale_y_log10(breaks=c(1:6,10*1:6), minor=NULL)+
  scale_y_continuous()                           +
  geom_ribbon(alpha=0.2)                         +
  geom_line(aes(x=t, y=hi))                      +
  geom_line(aes(x=t, y=lo))                      +
  ylab("Estimated trial duration (years)")       +
  xlab("Date of prediction (days)")             -> fig
save(fig, flat_predictions, file="fig/4.1.RData")
```

### Figure 4.1. Prediction band (25 and 75 percentiles) from flat prior.

```{r early-predictions-flat, fig.width=10, fig.height=5}
load("fig/4.1.RData"); print(fig)
```

```{r early-predictions-strong-prelims-2}
informative_predictions %>%
  mutate(lo=lo/365)                             %>%
  mutate(hi=hi/365)                             %>%
  ggplot(aes(x=t, ymin=lo, ymax=hi))             +
  # expand_limits(y=overall_range)                 +
  # scale_y_log10(breaks=c(1:6,10*1:6), minor=NULL)+
  scale_y_continuous()                           +
  geom_ribbon(alpha=0.2)                         +
  geom_line(aes(x=t, y=hi))                      +
  geom_line(aes(x=t, y=lo))                      +
  ylab("Estimated trial duration (years)")       +
  xlab("Date of prediction (days)")             -> fig
save(fig, file="fig/4.2.RData")
```

### Figure 4.2. Prediction band (25 and 75 percentiles) from strong prior.

```{r early-predictions-strong, fig.width=10, fig.height=5}
load("fig/4.2.RData"); print(fig)
```

```{r early-predictitons-weak-prelims-2}
weak_predictions %>%
  mutate(lo=lo/365)                             %>%
  mutate(hi=hi/365)                             %>%
  ggplot(aes(x=t, ymin=lo, ymax=hi))             +
  geom_ribbon(alpha=0.2)                         +
  # expand_limits(y=overall_range)                 +
  # scale_y_log10(breaks=c(1:6,10*1:6), minor=NULL)+
  scale_y_continuous()                           +
  geom_line(aes(x=t, y=hi))                      +
  geom_line(aes(x=t, y=lo))                      +
  ylab("Estimated trial duration (years)")       +
  xlab("Date of prediction (days)")             -> fig
save(fig, file="fig/4.3.RData")
```

### Figure 4.3. Prediction band (25 and 75 percentiles) from weak prior.

```{r early-predictions-weak, fig.width=10, fig.height=5, eval=TRUE}
load("fig/4.3.RData"); print(fig)
```

```{r rescaled-strong-prelims-2}
tx <- min(which(informative_predictions$lo>365*3.5))
lb <- paste0("(", tx, ",", 3.5, ")")
informative_predictions %>%
  mutate(lo=lo/365)                             %>%
  mutate(hi=hi/365)                             %>%
  ggplot(aes(x=t, ymin=lo, ymax=hi))             +
  scale_y_continuous()                           +
  geom_ribbon(alpha=0.2)                         +
  geom_line(aes(x=t, y=hi))                      +
  geom_line(aes(x=t, y=lo))                      +
  geom_vline(xintercept=tx)                      +
  geom_hline(yintercept=3.5)                     +
  geom_label(aes(x=tx, y=3.5, label=lb))         +
  ylab("Estimated trial duration (years)")       +
  xlab("Date of prediction (days)")             -> fig
save(fig, tx, lb, file="fig/4.4.RData")
```

### Figure 4.4 When to panic--strong prior

```{r rescaled-strong, fig.width=10, fig.height=5}
load("fig/4.4.RData"); print(fig)
```

```{r rescaled-weak-prelims-2}
tx <- min(which(weak_predictions$lo>365*3.5))
lb <- paste0("(", tx, ",", 3.5, ")")
weak_predictions                                %>%
  mutate(lo=lo/365)                             %>%
  mutate(hi=hi/365)                             %>%
  ggplot(aes(x=t, ymin=lo, ymax=hi))             +
  scale_y_continuous()                           +
  geom_ribbon(alpha=0.2)                         +
  geom_line(aes(x=t, y=hi))                      +
  geom_line(aes(x=t, y=lo))                      +
  geom_vline(xintercept=tx)                      +
  geom_hline(yintercept=3.5)                     +
  geom_label(aes(x=tx, y=3.5, label=lb))         +
  ylab("Estimated trial duration (years)")       +
  xlab("Date of prediction (days)")             -> fig
save(fig, tx, lb, file="fig/4.5.RData")
```

### Figure 4.5 When to panic--weak prior

```{r rescaled-weak, fig.width=10, fig.height=5}
load("fig/4.5.RData"); print(fig)
```

```{r save-everything}
save.image("4-early-predictions.RData")
```




