---
title: "Hierarchical binomial"
author: "Steve Simon"
date: "April 11, 2017"
output: html_document
---

```{r preliminaries}
getRversion()
Sys.time()
library(broom)
library(dplyr)
library(ggplot2)
library(magrittr)
library(rstan)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```


```{r read_data}
f <- "http://www.stat.columbia.edu/~gelman/book/data/rats.asc"
d <- read.table(file=f, skip=4)
d %<>% rename(x=V1, n=V2)
d
```

```{r stan_model}
f <- "gelman-rats.stan"
# Here's what's hiding in the file 
cat(readLines(f), sep="\n")
dat <- list(n=d$n, x=d$x, J=71)
fit01 <- stan(file=f, data=dat)
tidy(fit01)
```

```{r single_center_model_nice}
f <- "gelman-rats.stan"
# Here's what's hiding in the file 
cat(readLines(f), sep="\n")
dat <- list(n=c(20, 60), x=c(4,18), J=2)
fit02 <- stan(file=f, data=dat)
tidy(fit02)
```

```{r single_center_model_nasty}
f <- "gelman-rats.stan"
dat <- list(n=c(20, 60), x=c(4,54), J=2)
fit03 <- stan(file=f, data=dat)
tidy(fit03)
```

```{r reparameterized_model}
f <- "gelman-reparameterized.stan"
# Here's what's hiding in the file 
cat(readLines(f), sep="\n")
dat <- list(n=d$n, x=d$x, J=71)
fit04 <- stan(file=f, data=dat)
tidy(fit04)
```

